import numpy as np


def initialize_parameters(layer_dims):
    """
    :param layer_dims: an array of the dimensions of each layer in the network
    :return: a dictionary containing the initialized W and b parameters of each layer
    """
    params = {f'W{i + 1}': np.random.rand(layer_dims[i + 1], layer_dims[i]) for i in range(len(layer_dims) - 1)}
    params.update({f'b{i + 1}': np.zeros(layer_dims[i + 1]) for i in range(len(layer_dims) - 1)})

    return params


def linear_forward(A, W, b):
    """
    linear part of a layer's forward propagation.
    :param A: the activations of the previous layer
    :param W: the weight matrix of the current layer (of shape [size of current layer, size of previous layer])
    :param b: the bias vector of the current layer (of shape [size of current layer, 1])
    :return Z: the linear component of the activation function
    :return linear_cache: a dictionary containing A, W, b
    """
    A_c = np.expand_dims(A, axis=1)
    b_c = np.expand_dims(b, axis=1)
    Z = np.matmul(W, A_c) + b_c
    linear_cache = {'A': A, 'W': W, 'b': b}
    return Z, linear_cache


def softmax(Z):
    """
    :param Z: the linear component of the activation function
    :return A: the activations of the layer
    :return activation_cache: returns Z, which will be useful for the backpropagation
    """
    exp = np.exp(Z)
    z_softmax = exp / np.sum(exp)
    return z_softmax, {'Z': Z}


def safe_softmax(Z):
    Z_safe = Z - np.max(Z)
    return softmax(Z_safe)[0], {'Z': Z}


def relu(Z):
    """
    :param Z: the linear component of the activation function
    :return A: the activations of the layer
    :return activation_cach: returns Z, which will be useful for the backpropagation
    """
    A = np.apply_along_axis(lambda x: x if x > 0 else 0, 0, Z)
    return A, {'Z': Z}


def linear_activation_forward(A_prev, W, B, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer
    :param A_prev: activations of the previous layer
    :param W: the weights matrix of the current layer
    :param B: the bias vector of the current layer
    :param activation: the activation function to be used (a string, either “softmax” or “relu”)
    :return A: the activations of the current layer
    :return cache: a joint dictionary containing both linear_cache and activation_cache
    """
    return None, None


def L_model_forward(X, parameters, use_batchnorm):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SOFTMAX computation
    :param X: the data, numpy array of shape (input size, number of examples)
    :param parameters: the initialized W and b parameters of each layer
    :param use_batchnorm: a boolean flag used to determine whether to apply batchnorm after the activation
    :return AL: the last post-activation value
    :return caches: a list of all the cache objects generated by the linear_forward function
    """
    i = 1
    caches = {}
    num_layers = int(len(parameters) / 2)
    params_keys = parameters.keys()
    activations_prev = None

    for j in range(0, len(X[0])):  # TODO: omit the for and replace it with vectorized solution for X
        for i in range(1, num_layers):
            if i == 1:
                activations_prev = X[:, j]
            A_i, linear_activation_cache_i = linear_activation_forward(activations_prev, params_keys[f'W_{i}'],
                                                                       params_keys[f'b_{i}'], 'relu')
            caches.update({f'linear_activation_cache_{i}': linear_activation_cache_i})
            A_i = apply_batchnorm(A_i) if use_batchnorm else A_i
            activations_prev = A_i
        AL,  linear_activation_cache_L = linear_activation_forward(activations_prev, params_keys[f'W_{num_layers}'],
                                                                   params_keys[f'b_{num_layers}'], 'softmax')
        caches.update({f'linear_activation_cache_{i}': linear_activation_cache_L})

    return AL, caches
    pass


def compute_cost(AL, Y):
    """
    the cost function defined by equation
    :param AL:  probability vector corresponding to your label predictions, shape (num_of_classes, number of examples)
    :param Y: the labels vector (i.e. the ground truth)
    :return cost: the cross-entropy cost
    """
    pass


def apply_batchnorm(A):
    """
    performs batchnorm on the received activation values of a given layer.
    :param A: the activation values of a given layer
    :return NA: the normalized activation values, based on the formula learned in class
    """
    epsilon = 0.00000001  # prevent divding by zero
    mu = np.average(A)
    variance = np.var(A)
    A_norm = (A - mu) / np.sqrt(variance) if variance > 0 else (A - mu) / np.sqrt(variance + epsilon)

    return A_norm
